import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import LabelCard from '../components/LabelCard';
import BarChart from '../components/BarChart';
import RecentOrders from '../components/ExpenseHistory';
import PieChart from '@/components/PieChart';
import Form from '@/components/Form';
export default function Home({dark, showComponent, setShowComponent , dashboardValues, setDashboardValues, savedExpense, setSavedExpense, dashboardBalance, setDashboardBalance}) {

  useEffect(() => {
    setShowComponent(false);
  }, []);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className= {!dark ? 'bg-gray-100 min-h-screen' :'bg-[#1e202f] min-h-screen'} >
        <Header dark={dark}  showComponent={showComponent} setShowComponent={setShowComponent} dashboardValues={dashboardValues}/>
        <LabelCard savedExpense={savedExpense} dark={dark} dashboardValues={dashboardValues} dashboardBalance={dashboardBalance} setDashboardBalance={setDashboardBalance}/>
        <div className='p-4 grid md:grid-cols-3 md:grid-row-2 grid-cols-1 gap-4 '>
          <BarChart savedExpense={savedExpense} dark={dark} />
          <RecentOrders savedExpense={savedExpense} dark={dark} />
          {showComponent ? <Form showComponent ={showComponent} setShowComponent={setShowComponent} dashboardValues={dashboardValues} setDashboardValues={setDashboardValues} dark={dark}/> : null}
          <PieChart savedExpense={savedExpense} dark={dark} />
        </div>
      </main>
    </>
  );
}
